### ISSUE TITLE
Cannot install on python-3.10

### ISSUE THREAD

**Issue by arctic-pinguin** [asottile/importtime-waterfall#67]
This is on Arch Linux, with latest updates. Python is 3.10.4

Please let me know if you need additional information.

```
$ pip install --user importtime-waterfall
Collecting importtime-waterfall
  Downloading importtime_waterfall-1.0.0-py2.py3-none-any.whl (5.9 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/1d/5c/a299cf9f5748cc13f506934e2fa3ea5bbc9584946c0a773dc5104cb770f2/importtime_waterfall-1.0.0-py2.py3-none-any.whl#sha256=e65dbc4d23f0fd698ca3e8cfe767937b86f697e11790ac672aa86109792b3595 (from https://pypi.org/simple/importtime-waterfall/) (requires-python:>=3.7). Requested importtime-waterfall from https://files.pythonhosted.org/packages/1d/5c/a299cf9f5748cc13f506934e2fa3ea5bbc9584946c0a773dc5104cb770f2/importtime_waterfall-1.0.0-py2.py3-none-any.whl#sha256=e65dbc4d23f0fd698ca3e8cfe767937b86f697e11790ac672aa86109792b3595 has inconsistent version: filename has '1.0.0', but metadata has '1.0.0'
  Downloading importtime_waterfall-1.0.0.tar.gz (5.5 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/0c/f8/0d33c4d69344cb55116a656ef103b499f69a5f33f748ac0cd32c297cc955/importtime_waterfall-1.0.0.tar.gz#sha256=8140eb8e1774a39d426df82220f36b17d78ccbbba2adc75466979a315395f391 (from https://pypi.org/simple/importtime-waterfall/) (requires-python:>=3.7). Requested importtime-waterfall from https://files.pythonhosted.org/packages/0c/f8/0d33c4d69344cb55116a656ef103b499f69a5f33f748ac0cd32c297cc955/importtime_waterfall-1.0.0.tar.gz#sha256=8140eb8e1774a39d426df82220f36b17d78ccbbba2adc75466979a315395f391 has inconsistent version: filename has '1.0.0', but metadata has '1.0.0'
  Downloading importtime_waterfall-0.0.0-py2.py3-none-any.whl (4.3 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/d7/b0/b4fe097c99f1cac840b6c2d84b7e0b544c9e408980527fbe4d828f77025f/importtime_waterfall-0.0.0-py2.py3-none-any.whl#sha256=7be00b0e032c3f1730aa44cae6eeb49e5d8b9c60a6ee430df8d6d5d9ed6c2a12 (from https://pypi.org/simple/importtime-waterfall/) (requires-python:>=3.7). Requested importtime-waterfall from https://files.pythonhosted.org/packages/d7/b0/b4fe097c99f1cac840b6c2d84b7e0b544c9e408980527fbe4d828f77025f/importtime_waterfall-0.0.0-py2.py3-none-any.whl#sha256=7be00b0e032c3f1730aa44cae6eeb49e5d8b9c60a6ee430df8d6d5d9ed6c2a12 has inconsistent version: filename has '0.0.0', but metadata has '0.0.0'
  Downloading importtime_waterfall-0.0.0.tar.gz (4.3 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/ae/10/d861ebbbcc3b40e2bf3a1b24e2c16ceed41b80711a67101c5d6f9cbf7c97/importtime_waterfall-0.0.0.tar.gz#sha256=4d270c529c5c1abeeb33d83ae5a1f9c50a7cca93bf5ebddb49b8fa2a1b7cd51c (from https://pypi.org/simple/importtime-waterfall/) (requires-python:>=3.7). Requested importtime-waterfall from https://files.pythonhosted.org/packages/ae/10/d861ebbbcc3b40e2bf3a1b24e2c16ceed41b80711a67101c5d6f9cbf7c97/importtime_waterfall-0.0.0.tar.gz#sha256=4d270c529c5c1abeeb33d83ae5a1f9c50a7cca93bf5ebddb49b8fa2a1b7cd51c has inconsistent version: filename has '0.0.0', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement importtime-waterfall
ERROR: No matching distribution found for importtime-waterfall
```

Or via cloning:
```
$ git clone https://github.com/asottile/importtime-waterfall
$ cd importtime-waterfall
$ pip install --user .
Processing /home/REDACTED/tmp/importtime-waterfall
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 319, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 176, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 80, in from_requirement
    cands = build_iter_view(matches)
  File "/usr/lib/python3.10/site-packages/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 283, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/usr/lib/python3.10/site-packages/packaging/specifiers.py", line 790, in contains
    item = parse(item)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by asottile** [comment]
arch has patched pip in a broken way -- this isn't a problem of importtime-waterfall but your packager

**Comment by arctic-pinguin** [comment]
Thanks for the quick response. For anyone who finds this: upstream bug is this one https://bugs.archlinux.org/task/70104
